Demonstration version for deployment
Mavennet/Energy-Asset-Digital-Wallet pull request #1
Opened 2023-11-24 15:08 UTC by dave-promulgare

Here are the contracts, server, and web application files.

2024-01-18 17:37 UTC, mkhraisha requested changes
Please cleanup hello world, dummy endpoints, and hardcoded strings.

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/app.controller.ts
> +import { Controller, Get } from '@nestjs/common';
Cleanup the hello world

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/app.controller.spec.ts
> +
cleanup hello world

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/app.service.ts
> +
cleanup hello world

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/emission/emission.controller.ts
> +    @Get('getList')
should probably be 'list'

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/emission/emission.controller.ts
> +    @Post('getOne')
Remove the dummy gets?

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/emission/emission.service.ts
> +        //query.id = query._id;
remove commented line

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/emission/emission.service.ts
> +    async dummy(): Promise<any> {
remove dummy

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/oracle/oracle.controller.ts
> +    @Post('getMany')
Remove dummies

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/providers/database.providers.ts
> +      mongoose.connect('mongodb://192.168.2.192:27017/Mavennet'),
make this an env var

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/retire/retire.controller.ts
> +@Controller('retire')
similar dummy comment

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/retire/retire.service.ts
> +        //query.id = query._id;
remove line

2024-01-18 17:37 UTC, mkhraisha commented on wallet-rest-api/src/schemas/emissions.schema.ts
> +  //@Prop({ type: SchemaTypes.ObjectId, ref: 'Offsets', required:true })
delete unused code

2024-02-19 19:13 UTC, dave-promulgare commented on wallet-rest-api/src/app.controller.ts
> +import { Controller, Get } from '@nestjs/common';
Fixed in latest version

2024-02-19 19:13 UTC, dave-promulgare commented on wallet-rest-api/src/app.controller.spec.ts
> +
Fixed in latest version

2024-02-19 19:14 UTC, dave-promulgare commented on wallet-rest-api/src/app.service.ts
> +
Fixed in latest version

2024-02-19 19:14 UTC, dave-promulgare commented on wallet-rest-api/src/emission/emission.controller.ts
> +    @Get('getList')
Removed

2024-02-19 19:14 UTC, dave-promulgare commented on wallet-rest-api/src/emission/emission.controller.ts
> +    @Post('getOne')
Fixed in latest version

2024-02-19 19:15 UTC, dave-promulgare commented on wallet-rest-api/src/emission/emission.service.ts
> +        //query.id = query._id;
Fixed in latest version

2024-02-19 19:15 UTC, dave-promulgare commented on wallet-rest-api/src/emission/emission.service.ts
> +    async dummy(): Promise<any> {
Fixed in latest version

2024-02-19 19:15 UTC, dave-promulgare commented on wallet-rest-api/src/oracle/oracle.controller.ts
> +    @Post('getMany')
Fixed in latest version

2024-02-19 19:15 UTC, dave-promulgare commented on wallet-rest-api/src/providers/database.providers.ts
> +      mongoose.connect('mongodb://192.168.2.192:27017/Mavennet'),
Fixed in latest version

2024-02-19 19:15 UTC, dave-promulgare commented on wallet-rest-api/src/retire/retire.controller.ts
> +@Controller('retire')
Fixed in latest version

2024-02-19 19:15 UTC, dave-promulgare commented on wallet-rest-api/src/retire/retire.service.ts
> +        //query.id = query._id;
Fixed in latest version

2024-02-19 19:15 UTC, dave-promulgare commented on wallet-rest-api/src/schemas/emissions.schema.ts
> +  //@Prop({ type: SchemaTypes.ObjectId, ref: 'Offsets', required:true })
Fixed in latest version

2024-02-19 19:16 UTC, dave-promulgare commented
I have removed the Hello World call, the dummy calls, and the commented out code.  I have compiled and run the code and everything is working.

2024-02-22 14:52 UTC, mkhraisha approved these changes

2024-02-22 14:52 UTC, merged